travis:
  secure:
    BINSTAR_TOKEN: jDCTGReYXzeZ68BhtjwuHvDXdINBh8UBUe/TZ+q8X+a22C7tuQD9yyJLB1iqSn9pij9VrqGZvwLqct+60k1/CkdHGr2itqiZczOgjgPxQqtAQ3SR6V+OKPQjh0Zz5zbhea2jSCK2H15awIbLroKEm2kNA4eE3O0tzUPXhNVKGywYSFs+Fq+PR2YSElf2CK6yRB2o0u9jBMF5bekHbU10knnvyIPDT7sR53htS3fwM9V2re07OgsI3itRh7MCqP/Sh4vuEwkyI7UCTfAh3AF1FvCmBQMIAO3Ib4kK+uMvQfKjUwUhmfAh/q+EGE6HLhp3TWQ2qtXaRzCBfuEk5w+iZP2qTSvHjSdnhqUeVTG/GOsqJBGVfkbglbgjsOPAd6lsgt7IsidOQXG2ZBnGU21znb3HujprKC+ddOe/iWfLCql7oidVOJYhwxGkKQrNh1gjtshArolaI9oh7Oxc+KD4JQ/WGASuZKEcjHYJYXp5JD3W55tRYHZL9ZuzVObMVKFbgtwxYikOUTgTJPTSkQnV1uQ2nf2geuOEH0dYq4VVVXN5gbx83i59FBLme2w1x86v7wOUFQc/TfSYeKcIm/9aUmrFxXhbCNkhArHCEZvPuE6g90W7yL20FXl2x2VNM9G8leqJ1DZidc9RUJQeEajZII78z53NuxozPVrGo59U+4M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
