travis:
  secure:
    BINSTAR_TOKEN: ayKomGPKuAdvH5whYSNjEbyk1jdGbDKQ3jrI5zl5c9+H7AXxos3Xf8deixfLMazlThGxPipoT6jHXKiqALsMcmAITjEhqdfsJi7+dFNMNt/UjSPMrNExmM8u4Lhh1fqmSnY7ySk+rsRAxj34bmOzZ9i4WOjS8OP/JCVHrADvrP9el8qXAwafh/hZYsI0dAecPtgeai2e0df4KpRokuNChpaPgXLuimYVWOtV3Zpra3Xmgfus9cw7j1L5zUykNYI7uQhr7uhM1lPodeRbbDPh0camvBCbhgjPzy6e7/uDcoZK3GBpuUP8Rjj2YvwgT4MNB433BSl+RrOaaywkVzc/piwybCWuYc6WmgfV8GaDKsn2+ahGJjTJJdxQTNYqMp7yroODXFeng8a8knQXVUGSD2o0117axXI22xTC8WOG9ohI8ZhGaKZXUT+g8Wu6hmhvvElHLtoluJfX+9Tt8EQoHlIZmdFjQRZoH8RViLJflG2RlXA49cZjSnIAxO+s4nu2HzMZv8rBXCqaR0E8Ybl7WJI+ylCSNS4pF189N92ITFY+uidQ533LZWvCh0pYcCkt+e7a1AHV26pSkYMMtT9WK2orIjW8x4p/jR8wxyHyG/4kH1w6uQKwO+siHf3Uvoo92VzL6JFd7xAiXAMgFS5ryfq6XIeE/LoXxHHaCPoVjL0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
